#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 14, 2020 10:09:29 PM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background $vTcl(actual_gui_bg) -cursor arrow 
    wm focusmodel $top passive
    wm geometry $top 740x581+361+69
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Bolt Analysis Tool - BAT"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men45" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font {} -foreground $vTcl(pr,menufgcolor) -label File 
    menu $site_3_0.men45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men45 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font {} \
        -foreground $vTcl(pr,menufgcolor) -label {Open *.inp File} 
    $site_3_0.men45 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men45 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font {} \
        -foreground $vTcl(pr,menufgcolor) -label Exit 
    $site_3_0 add cascade \
        -menu "$site_3_0.men45" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font {} -foreground $vTcl(pr,menufgcolor) -label File \
        -menu "$site_3_0.men46" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font {} -foreground $vTcl(pr,menufgcolor) -label Help 
    menu $site_3_0.men46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men46 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font {} \
        -foreground $vTcl(pr,menufgcolor) -label Info 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo48 \
        -width 702 -height 540 -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tNo48" "TNotebook" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo48.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook_Joint_Input" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text {Joint Input} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    labelframe $site_4_0.lab49 \
        -font TkDefaultFont -foreground black -text {Bolt Definition} \
        -background $vTcl(actual_gui_bg) -height 395 -width 660 
    vTcl:DefineAlias "$site_4_0.lab49" "Labelframe_Bolt_Def" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab49
    ttk::combobox $site_5_0.tCo64 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo64" "TCombobox_Bolt" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab65 \
        -anchor e -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Joint MOS Type:} 
    vTcl:DefineAlias "$site_5_0.lab65" "Label_Jt" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad66 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {MIN (STD)} 
    vTcl:DefineAlias "$site_5_0.rad66" "Radiobutton_Jt_min" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad67 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text MEAN 
    vTcl:DefineAlias "$site_5_0.rad67" "Radiobutton_Jt_mean" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab68 \
        -anchor e -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Bolt: 
    vTcl:DefineAlias "$site_5_0.lab68" "Label_Bolt" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab69 \
        -anchor e -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Bolt Material:} 
    vTcl:DefineAlias "$site_5_0.lab69" "Label_Bolt_Material" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo70 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo70" "TCombobox_Bolt_Material" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Coefficient of Friction - Bolt Head:} 
    vTcl:DefineAlias "$site_5_0.tLa71" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa72 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text MIN 
    vTcl:DefineAlias "$site_5_0.tLa72" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa73 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text MAX 
    vTcl:DefineAlias "$site_5_0.tLa73" "TLabel2_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent79 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent79" "Entry_Cof_Head_Min" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent80 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent80" "Entry_Cof_Head_Max" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa81 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Coefficient of Friction - Thread:} 
    vTcl:DefineAlias "$site_5_0.tLa81" "TLabel1_8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent82 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent82" "Entry_Cof_Thread_Min" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent83 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent83" "Entry_Cof_Thread_Max" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa84 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Tightening Torque:} 
    vTcl:DefineAlias "$site_5_0.tLa84" "TLabel1_9" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_5_0.tSe85
    vTcl:DefineAlias "$site_5_0.tSe85" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent86 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent86" "Entry_Tight_Torque" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa87 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Nm 
    vTcl:DefineAlias "$site_5_0.tLa87" "TLabel2_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa88 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Torque Tolerance of Tightening Device:} 
    vTcl:DefineAlias "$site_5_0.tLa88" "TLabel1_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa89 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Nm 
    vTcl:DefineAlias "$site_5_0.tLa89" "TLabel2_12" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent90 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent90" "Entry_Torque_Tol" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa91 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Locking Device Used:} 
    vTcl:DefineAlias "$site_5_0.tLa91" "TLabel1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa92 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Torque Tolerance of Tightening Device:} 
    vTcl:DefineAlias "$site_5_0.tLa92" "TLabel1_11" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad94 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text NO 
    vTcl:DefineAlias "$site_5_0.rad94" "Radiobutton_Lock_No" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad95 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text YES 
    vTcl:DefineAlias "$site_5_0.rad95" "Radiobutton_Lock_Yes" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa96 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Nm 
    vTcl:DefineAlias "$site_5_0.tLa96" "TLabel2_13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent97 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 60 
    vTcl:DefineAlias "$site_5_0.ent97" "Entry_Prevailing_Torque" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa98 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Tp: 
    vTcl:DefineAlias "$site_5_0.tLa98" "TLabel2_13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent99 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 100 
    vTcl:DefineAlias "$site_5_0.ent99" "Entry_Loading_Plane_Factor" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tCo64 \
        -in $site_5_0 -x 0 -relx 0.288 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.283 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab65 \
        -in $site_5_0 -x 0 -relx 0.03 -y 0 -rely 0.078 -width 0 \
        -relwidth 0.212 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad66 \
        -in $site_5_0 -x 0 -relx 0.273 -y 0 -rely 0.076 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad67 \
        -in $site_5_0 -x 0 -relx 0.439 -y 0 -rely 0.078 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab68 \
        -in $site_5_0 -x 0 -relx 0.03 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.212 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab69 \
        -in $site_5_0 -x 0 -relx 0.03 -y 0 -rely 0.234 -width 0 \
        -relwidth 0.212 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo70 \
        -in $site_5_0 -x 0 -relx 0.288 -y 0 -rely 0.234 -width 0 \
        -relwidth 0.283 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa71 \
        -in $site_5_0 -x 0 -relx 0.045 -y 0 -rely 0.416 -width 0 \
        -relwidth 0.359 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa72 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.338 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa73 \
        -in $site_5_0 -x 0 -relx 0.652 -y 0 -rely 0.338 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent79 \
        -in $site_5_0 -x 0 -relx 0.439 -y 0 -rely 0.416 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent80 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.416 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa81 \
        -in $site_5_0 -x 0 -relx 0.045 -y 0 -rely 0.494 -width 0 \
        -relwidth 0.359 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent82 \
        -in $site_5_0 -x 0 -relx 0.439 -y 0 -rely 0.494 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent83 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.494 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa84 \
        -in $site_5_0 -x 0 -relx 0.212 -y 0 -rely 0.675 -width 0 \
        -relwidth 0.223 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tSe85 \
        -in $site_5_0 -x 0 -relx 0.039 -y 0 -rely 0.6 -width 0 \
        -relwidth 0.926 -height 0 -relheight 0.005 -anchor nw \
        -bordermode inside 
    place $site_5_0.ent86 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.675 -width 100 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa87 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.675 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa88 \
        -in $site_5_0 -x 0 -relx 0.015 -y 0 -rely 0.753 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa89 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.753 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent90 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.753 -width 100 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa91 \
        -in $site_5_0 -x 0 -relx 0.015 -y 0 -rely 0.831 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa92 \
        -in $site_5_0 -x 0 -relx 0.015 -y 0 -rely 0.909 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad94 \
        -in $site_5_0 -x 0 -relx 0.455 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad95 \
        -in $site_5_0 -x 0 -relx 0.561 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa96 \
        -in $site_5_0 -x 0 -relx 0.894 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent97 \
        -in $site_5_0 -x 0 -relx 0.803 -y 0 -rely 0.835 -width 60 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa98 \
        -in $site_5_0 -x 0 -relx 0.727 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent99 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.911 -width 100 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    label $site_4_0.lab51 \
        -anchor e -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Method: 
    vTcl:DefineAlias "$site_4_0.lab51" "Label_Method" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad55 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ESA PSS-03} 
    vTcl:DefineAlias "$site_4_0.rad55" "Radiobutton_Esapss" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad56 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {VDI 2230} 
    vTcl:DefineAlias "$site_4_0.rad56" "Radiobutton_VDI2230" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad57 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ECSS bla} 
    vTcl:DefineAlias "$site_4_0.rad57" "Radiobutton_ECSS" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab58 \
        -anchor e -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Project Title:} 
    vTcl:DefineAlias "$site_4_0.lab58" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 536 
    vTcl:DefineAlias "$site_4_0.ent59" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.943 -height 0 -relheight 0.8 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 0 -relx 0.027 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.143 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad55 \
        -in $site_4_0 -x 0 -relx 0.171 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.183 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad56 \
        -in $site_4_0 -x 0 -relx 0.643 -y 0 -rely 0.04 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $site_4_0.rad57 \
        -in $site_4_0 -x 0 -relx 0.4 -y 0 -rely 0.04 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $site_4_0.lab58 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.101 -width 0 \
        -relwidth 0.143 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent59 \
        -in $site_4_0 -x 0 -relx 0.2 -y 0 -rely 0.101 -width 536 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook_Loads" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text Loads -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo48.t1
    frame $top.tNo48.t2 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t2" "TNotebook_Calculate" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t2 \
        -padding 0 -sticky nsew -state normal -text Calculate -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo48.t2
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.034 -width 0 -relwidth 0.949 \
        -height 0 -relheight 0.929 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

