#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 17, 2020 10:31:56 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global joint_mos_type
    joint_mos_type = tk.IntVar()
    global locking_device
    locking_device = tk.IntVar()
    global method_sel
    method_sel = tk.IntVar()
    global selectedButton
    selectedButton = tk.IntVar()
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    # init gui with the default settings
    init_config()

# set the gui with the default settings
def init_config():
    w.Radiobutton_Esapss.select()
    w.Radiobutton_ECSS.configure(state = "disabled")
    w.Radiobutton_VDI2230.configure(state = "disabled")
    w.Radiobutton_Jt_min.select()
    w.Radiobutton_Lock_No.select()
    w.Entry_Prevailing_Torque.configure(state = "disabled")
    w.Entry_Loading_Plane_Factor.insert(0, "0.5")

# method selection radio-buttons
def radio_ecss(p1): pass
def radio_esapss(p1): pass
def radio_vdi2230(p1): pass

# locking device radio-buttons
def locking_device_no(p1):
    w.Entry_Prevailing_Torque.configure(state = "disabled")
def locking_device_yes(p1):
    w.Entry_Prevailing_Torque.configure(state = "normal")

# exit BAT via File-Exit
def quit_menu():
    root.quit()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import bat_gui
    bat_gui.vp_start_gui()





