#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 25, 2020 10:31:25 AM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background $vTcl(actual_gui_bg) -cursor arrow \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 823x567+283+108
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Bolt Analysis Tool - BAT"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men45" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label File 
    menu $site_3_0.men45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men45 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#open_inp_menu} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Open *.inp File} 
    $site_3_0.men45 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men45 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#quit_menu} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Exit 
    $site_3_0 add cascade \
        -menu "$site_3_0.men45" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label File -menu "$site_3_0.men46" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Help 
    menu $site_3_0.men46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men46 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#info_menu} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Info 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo48 \
        -width 702 -height 540 -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tNo48" "TNotebook" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo48.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook_Bolt" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text Bolt -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    labelframe $site_4_0.lab49 \
        -font TkDefaultFont -foreground black -text {Bolt Definition} \
        -background $vTcl(actual_gui_bg) -height 411 -highlightcolor black \
        -width 751 
    vTcl:DefineAlias "$site_4_0.lab49" "Labelframe_Bolt_Def" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab49
    ttk::combobox $site_5_0.tCo64 \
        -font TkTextFont -textvariable combo_bolt -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo64" "TCombobox_Bolt" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Joint MOS Type:} 
    vTcl:DefineAlias "$site_5_0.lab65" "Label_Jt" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {MIN (STD)} -value 0 -variable joint_mos_type 
    vTcl:DefineAlias "$site_5_0.rad66" "Radiobutton_Jt_min" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text MEAN -value 1 -variable joint_mos_type 
    vTcl:DefineAlias "$site_5_0.rad67" "Radiobutton_Jt_mean" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Bolt: 
    vTcl:DefineAlias "$site_5_0.lab68" "Label_Bolt" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Bolt Material:} 
    vTcl:DefineAlias "$site_5_0.lab69" "Label_Bolt_Material" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo70 \
        -font TkTextFont -textvariable combo_bolt_mat -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tCo70" "TCombobox_Bolt_Material" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Coefficient of Friction - Bolt Head:} 
    vTcl:DefineAlias "$site_5_0.tLa71" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa72 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text MIN 
    vTcl:DefineAlias "$site_5_0.tLa72" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa73 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text MAX 
    vTcl:DefineAlias "$site_5_0.tLa73" "TLabel2_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent79 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent79" "Entry_Cof_Head_Min" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent80 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent80" "Entry_Cof_Head_Max" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa81 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Coefficient of Friction - Thread:} 
    vTcl:DefineAlias "$site_5_0.tLa81" "TLabel1_8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent82 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent82" "Entry_Cof_Thread_Min" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent83 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent83" "Entry_Cof_Thread_Max" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa84 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Tightening Torque:} 
    vTcl:DefineAlias "$site_5_0.tLa84" "TLabel1_9" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_5_0.tSe85
    vTcl:DefineAlias "$site_5_0.tSe85" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent86 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent86" "Entry_Tight_Torque" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa87 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Nm 
    vTcl:DefineAlias "$site_5_0.tLa87" "TLabel2_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa88 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Torque Tolerance of Tightening Device:} 
    vTcl:DefineAlias "$site_5_0.tLa88" "TLabel1_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa89 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Nm 
    vTcl:DefineAlias "$site_5_0.tLa89" "TLabel2_12" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent90 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 
    vTcl:DefineAlias "$site_5_0.ent90" "Entry_Torque_Tol" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa91 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Locking Device Used:} 
    vTcl:DefineAlias "$site_5_0.tLa91" "TLabel1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa92 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Loading Plane Factor:} 
    vTcl:DefineAlias "$site_5_0.tLa92" "TLabel1_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad94 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text NO -value 0 -variable locking_device 
    vTcl:DefineAlias "$site_5_0.rad94" "Radiobutton_Lock_No" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.rad94 <Button-1> {
        lambda e: locking_device_no(e)
    }
    radiobutton $site_5_0.rad95 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text YES -value 1 -variable locking_device 
    vTcl:DefineAlias "$site_5_0.rad95" "Radiobutton_Lock_Yes" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.rad95 <Button-1> {
        lambda e: locking_device_yes(e)
    }
    ttk::label $site_5_0.tLa96 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Nm 
    vTcl:DefineAlias "$site_5_0.tLa96" "TLabel2_13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent97 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 60 
    vTcl:DefineAlias "$site_5_0.ent97" "Entry_Prevailing_Torque" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa98 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor center -justify left \
        -text Tp: 
    vTcl:DefineAlias "$site_5_0.tLa98" "TLabel2_2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent99 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 100 
    vTcl:DefineAlias "$site_5_0.ent99" "Entry_Loading_Plane_Factor" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tCo64 \
        -in $site_5_0 -x 0 -relx 0.288 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.283 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab65 \
        -in $site_5_0 -x 0 -relx 0.03 -y 0 -rely 0.078 -width 0 \
        -relwidth 0.212 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad66 \
        -in $site_5_0 -x 0 -relx 0.273 -y 0 -rely 0.076 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad67 \
        -in $site_5_0 -x 0 -relx 0.439 -y 0 -rely 0.078 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab68 \
        -in $site_5_0 -x 0 -relx 0.03 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.212 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab69 \
        -in $site_5_0 -x 0 -relx 0.03 -y 0 -rely 0.234 -width 0 \
        -relwidth 0.212 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo70 \
        -in $site_5_0 -x 0 -relx 0.288 -y 0 -rely 0.234 -width 0 \
        -relwidth 0.283 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa71 \
        -in $site_5_0 -x 0 -relx 0.027 -y 0 -rely 0.414 -width 0 \
        -relwidth 0.359 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa72 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.338 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa73 \
        -in $site_5_0 -x 0 -relx 0.652 -y 0 -rely 0.338 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent79 \
        -in $site_5_0 -x 0 -relx 0.439 -y 0 -rely 0.416 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent80 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.416 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa81 \
        -in $site_5_0 -x 0 -relx 0.027 -y 0 -rely 0.487 -width 0 \
        -relwidth 0.359 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent82 \
        -in $site_5_0 -x 0 -relx 0.439 -y 0 -rely 0.494 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent83 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.494 -width 100 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa84 \
        -in $site_5_0 -x 0 -relx 0.212 -y 0 -rely 0.675 -width 0 \
        -relwidth 0.223 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tSe85 \
        -in $site_5_0 -x 0 -relx 0.039 -y 0 -rely 0.6 -width 0 \
        -relwidth 0.926 -height 0 -relheight 0.005 -anchor nw \
        -bordermode inside 
    place $site_5_0.ent86 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.675 -width 100 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa87 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.675 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa88 \
        -in $site_5_0 -x 0 -relx 0.015 -y 0 -rely 0.753 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa89 \
        -in $site_5_0 -x 0 -relx 0.621 -y 0 -rely 0.753 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent90 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.753 -width 100 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa91 \
        -in $site_5_0 -x 0 -relx 0.015 -y 0 -rely 0.831 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa92 \
        -in $site_5_0 -x 0 -relx 0.015 -y 0 -rely 0.909 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.065 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad94 \
        -in $site_5_0 -x 0 -relx 0.455 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad95 \
        -in $site_5_0 -x 0 -relx 0.583 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tLa96 \
        -in $site_5_0 -x 0 -relx 0.894 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent97 \
        -in $site_5_0 -x 0 -relx 0.803 -y 0 -rely 0.835 -width 60 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa98 \
        -in $site_5_0 -x 0 -relx 0.727 -y 0 -rely 0.835 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent99 \
        -in $site_5_0 -x 0 -relx 0.47 -y 0 -rely 0.911 -width 100 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    label $site_4_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Method: 
    vTcl:DefineAlias "$site_4_0.lab51" "Label_Method" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ESA PSS-03} -value 0 -variable method_sel 
    vTcl:DefineAlias "$site_4_0.rad55" "Radiobutton_Esapss" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.rad55 <Button-1> {
        lambda e: radio_esapss(e)
    }
    radiobutton $site_4_0.rad56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {VDI 2230} -value 2 -variable method_sel 
    vTcl:DefineAlias "$site_4_0.rad56" "Radiobutton_VDI2230" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.rad56 <Button-1> {
        lambda e: radio_vdi2230(e)
    }
    radiobutton $site_4_0.rad57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ECSS bla} -value 1 -variable method_sel 
    vTcl:DefineAlias "$site_4_0.rad57" "Radiobutton_ECSS" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.rad57 <Button-1> {
        lambda e: radio_ecss(e)
    }
    label $site_4_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Project Title:} 
    vTcl:DefineAlias "$site_4_0.lab58" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 606 
    vTcl:DefineAlias "$site_4_0.ent59" "Entry_project_name" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.025 -y 0 -rely 0.175 -width 0 \
        -relwidth 0.955 -height 0 -relheight 0.8 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 0 -relx 0.027 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.143 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad55 \
        -in $site_4_0 -x 0 -relx 0.171 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.183 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad56 \
        -in $site_4_0 -x 0 -relx 0.643 -y 0 -rely 0.039 -width 0 \
        -relwidth 0.2 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad57 \
        -in $site_4_0 -x 0 -relx 0.4 -y 0 -rely 0.04 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $site_4_0.lab58 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.101 -width 0 \
        -relwidth 0.143 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent59 \
        -in $site_4_0 -x 0 -relx 0.2 -y 0 -rely 0.101 -width 606 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t3 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t3" "TNotebook_CP" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t3 \
        -padding 0 -sticky nsew -state normal -text {Clamped Parts} -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo48.t3
    labelframe $site_4_1.lab53 \
        -font TkDefaultFont -foreground black \
        -text {Clamped Parts Definition} -background $vTcl(actual_gui_bg) \
        -height 475 -highlightcolor black -width 740 
    vTcl:DefineAlias "$site_4_1.lab53" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.lab53
    label $site_5_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Minimum CoF between Clamped Parts:} 
    vTcl:DefineAlias "$site_5_0.lab54" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Through Hole Diameter:} 
    vTcl:DefineAlias "$site_5_0.lab55" "Label3_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Number of Shear Planes:} 
    vTcl:DefineAlias "$site_5_0.lab56" "Label3_8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent57 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 126 
    vTcl:DefineAlias "$site_5_0.ent57" "Entry_cof_clamp" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_5_0.spi58 \
        -activebackground #f9f9f9 -background white -font TkDefaultFont \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable spinbox_nmbr_shear_planes -to 100.0 
    vTcl:DefineAlias "$site_5_0.spi58" "Spinbox_nmbr_shear_planes" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 126 
    vTcl:DefineAlias "$site_5_0.ent59" "Entry_throughhole_diameter" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text mm 
    vTcl:DefineAlias "$site_5_0.lab60" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Substitutional Diameter - DA:} 
    vTcl:DefineAlias "$site_5_0.lab61" "Label3_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent62 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 126 
    vTcl:DefineAlias "$site_5_0.ent62" "Entry_subst_da" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text mm 
    vTcl:DefineAlias "$site_5_0.lab63" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text DELETE 
    vTcl:DefineAlias "$site_5_0.but70" "Button_del_cp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but70 <Button-1> {
        lambda e: button_delete_cp(e)
    }
    labelframe $site_5_0.lab71 \
        -font TkDefaultFont -foreground black -text {Define Clamp Part (i)} \
        -background $vTcl(actual_gui_bg) -height 96 -highlightcolor black \
        -width 519 
    vTcl:DefineAlias "$site_5_0.lab71" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.lab71
    ttk::combobox $site_6_0.tCo72 \
        -font TkTextFont -textvariable combo_clamp_mat -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_6_0.tCo72" "TCombobox_cp_mat" vTcl:WidgetProc "Toplevel1" 1
    label $site_6_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Material: 
    vTcl:DefineAlias "$site_6_0.lab73" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_6_0.lab74 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Thickness: 
    vTcl:DefineAlias "$site_6_0.lab74" "Label5_11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_6_0.ent75 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 126 
    vTcl:DefineAlias "$site_6_0.ent75" "Entry_cp_thk" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text ADD 
    vTcl:DefineAlias "$site_6_0.but76" "Button_add_cp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_6_0.but76 <Button-1> {
        lambda e: button_add_cp(e)
    }
    label $site_6_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text mm 
    vTcl:DefineAlias "$site_6_0.lab44" "Label4_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.tCo72 \
        -in $site_6_0 -x 0 -relx 0.045 -y 0 -rely 0.526 -width 0 \
        -relwidth 0.322 -height 0 -relheight 0.263 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab73 \
        -in $site_6_0 -x 0 -relx 0.045 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.311 -height 0 -relheight 0.263 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab74 \
        -in $site_6_0 -x 0 -relx 0.43 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.248 -height 0 -relheight 0.263 -anchor nw \
        -bordermode ignore 
    place $site_6_0.ent75 \
        -in $site_6_0 -x 0 -relx 0.43 -y 0 -rely 0.521 -width 126 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but76 \
        -in $site_6_0 -x 0 -relx 0.829 -y 0 -rely 0.313 -width 71 -relwidth 0 \
        -height 41 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab44 \
        -in $site_6_0 -x 0 -relx 0.674 -y 0 -rely 0.521 -width 0 \
        -relwidth 0.114 -height 0 -relheight 0.26 -anchor nw \
        -bordermode ignore 
    button $site_5_0.but77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text DOWN 
    vTcl:DefineAlias "$site_5_0.but77" "Button_cp_down" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but77 <Button-1> {
        lambda e: button_down_cp(e)
    }
    button $site_5_0.but78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text UP 
    vTcl:DefineAlias "$site_5_0.but78" "Button_cp_up" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but78 <Button-1> {
        lambda e: button_up_cp(e)
    }
    listbox $site_5_0.lis80 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -height 136 -highlightcolor black -selectbackground #c4c4c4 \
        -selectforeground black -width 656 
    $site_5_0.lis80 configure -font "TkFixedFont"
    $site_5_0.lis80 insert end text
    vTcl:DefineAlias "$site_5_0.lis80" "Listbox_clamped_parts" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text Auto-DA -variable cheVal_DA 
    vTcl:DefineAlias "$site_5_0.che44" "Checkbutton_DA" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.che44 <Button-1> {
        lambda e: auto_da_checkbox(e)
    }
    ttk::combobox $site_5_0.tCo45 \
        -font TkTextFont -textvariable combo_shim -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo45" "TCombobox_shim" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo47 \
        -font TkTextFont -textvariable combo_shim_mat -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo47" "TCombobox_shim_mat" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Use Shim:} -variable cheVal_use_shim 
    vTcl:DefineAlias "$site_5_0.che48" "Checkbutton_use_shim" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.che48 <Button-1> {
        lambda e: use_shim_checkbox(e)
    }
    place $site_5_0.lab54 \
        -in $site_5_0 -x 0 -relx 0.014 -y 0 -rely 0.065 -width 0 \
        -relwidth 0.432 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 0 -relx 0.014 -y 0 -rely 0.194 -width 0 \
        -relwidth 0.432 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab56 \
        -in $site_5_0 -x 0 -relx 0.014 -y 0 -rely 0.13 -width 0 \
        -relwidth 0.432 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent57 \
        -in $site_5_0 -x 0 -relx 0.477 -y 0 -rely 0.065 -width 126 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.spi58 \
        -in $site_5_0 -x 0 -relx 0.477 -y 0 -rely 0.13 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent59 \
        -in $site_5_0 -x 0 -relx 0.477 -y 0 -rely 0.194 -width 126 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab60 \
        -in $site_5_0 -x 0 -relx 0.655 -y 0 -rely 0.194 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab61 \
        -in $site_5_0 -x 0 -relx 0.014 -y 0 -rely 0.259 -width 0 \
        -relwidth 0.432 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent62 \
        -in $site_5_0 -x 0 -relx 0.477 -y 0 -rely 0.259 -width 126 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab63 \
        -in $site_5_0 -x 0 -relx 0.655 -y 0 -rely 0.259 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but70 \
        -in $site_5_0 -x 0 -relx 0.805 -y 0 -rely 0.583 -width 101 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab71 \
        -in $site_5_0 -x 0 -relx 0.055 -y 0 -rely 0.432 -width 0 \
        -relwidth 0.708 -height 0 -relheight 0.207 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but77 \
        -in $site_5_0 -x 0 -relx 0.805 -y 0 -rely 0.518 -width 101 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but78 \
        -in $site_5_0 -x 0 -relx 0.805 -y 0 -rely 0.454 -width 101 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lis80 \
        -in $site_5_0 -x 0 -relx 0.055 -y 0 -rely 0.67 -width 0 \
        -relwidth 0.895 -height 0 -relheight 0.294 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che44 \
        -in $site_5_0 -x 0 -relx 0.723 -y 0 -rely 0.259 -width 0 \
        -relwidth 0.146 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo45 \
        -in $site_5_0 -x 0 -relx 0.477 -y 0 -rely 0.346 -width 0 \
        -relwidth 0.173 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo47 \
        -in $site_5_0 -x 0 -relx 0.682 -y 0 -rely 0.346 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che48 \
        -in $site_5_0 -x 0 -relx 0.314 -y 0 -rely 0.346 -width 0 \
        -relwidth 0.132 -height 0 -relheight 0.05 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab53 \
        -in $site_4_1 -x 0 -relx 0.026 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.941 -height 0 -relheight 0.924 -anchor nw \
        -bordermode ignore 
    frame $top.tNo48.t4 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t4" "TNotebook_FOS" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t4 \
        -padding 0 -sticky nsew -state normal -text FOS -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo48.t4
    labelframe $site_4_2.lab44 \
        -font TkDefaultFont -foreground black -text {Factors of Safety - FOS} \
        -background $vTcl(actual_gui_bg) -height 475 -highlightcolor black \
        -width 730 
    vTcl:DefineAlias "$site_4_2.lab44" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_2.lab44
    label $site_5_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Factor of Safety Yield - FOS_y:} 
    vTcl:DefineAlias "$site_5_0.lab45" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Factor of Safety Ultimate - FOS_u:} 
    vTcl:DefineAlias "$site_5_0.lab46" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Factor of Safety Gapping - FOS_gap:} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Factor of Safety Slippage - FOS_slip:} 
    vTcl:DefineAlias "$site_5_0.lab48" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent49 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 116 
    vTcl:DefineAlias "$site_5_0.ent49" "Entry_fos_y" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent50 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 116 
    vTcl:DefineAlias "$site_5_0.ent50" "Entry_fos_u" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 116 
    vTcl:DefineAlias "$site_5_0.ent51" "Entry_fos_slip" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent52 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 116 
    vTcl:DefineAlias "$site_5_0.ent52" "Entry_fos_gap" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab45 \
        -in $site_5_0 -x 0 -relx 0.082 -y 0 -rely 0.084 -width 0 \
        -relwidth 0.326 -height 0 -relheight 0.053 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab46 \
        -in $site_5_0 -x 0 -relx 0.082 -y 0 -rely 0.168 -width 0 \
        -relwidth 0.326 -height 0 -relheight 0.053 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 0 -relx 0.082 -y 0 -rely 0.337 -width 0 \
        -relwidth 0.326 -height 0 -relheight 0.053 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab48 \
        -in $site_5_0 -x 0 -relx 0.027 -y 0 -rely 0.253 -width 0 \
        -relwidth 0.381 -height 0 -relheight 0.053 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent49 \
        -in $site_5_0 -x 0 -relx 0.452 -y 0 -rely 0.084 -width 116 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent50 \
        -in $site_5_0 -x 0 -relx 0.452 -y 0 -rely 0.168 -width 116 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent51 \
        -in $site_5_0 -x 0 -relx 0.452 -y 0 -rely 0.253 -width 116 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent52 \
        -in $site_5_0 -x 0 -relx 0.452 -y 0 -rely 0.337 -width 116 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab44 \
        -in $site_4_2 -x 0 -relx 0.025 -y 0 -rely 0.039 -width 0 \
        -relwidth 0.929 -height 0 -relheight 0.924 -anchor nw \
        -bordermode ignore 
    frame $top.tNo48.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook_Loads" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text Loads -image {} \
        -compound left -underline -1 
    set site_4_3  $top.tNo48.t1
    frame $top.tNo48.t2 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t2" "TNotebook_Calculate" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t2 \
        -padding 0 -sticky nsew -state normal -text Calculate -image {} \
        -compound none -underline -1 
    set site_4_4  $top.tNo48.t2
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 0 -relx 0.024 -y 0 -rely 0.035 -width 0 -relwidth 0.949 \
        -height 0 -relheight 0.929 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

