#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 18, 2020 10:06:41 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import src.functions.bat_gui_support as bat_gui_support

def vp_start_gui(materials, bolts):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    bat_gui_support.set_Tk_var()
    top = Toplevel1 (root)
    bat_gui_support.init(root, top, materials, bolts)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    bat_gui_support.set_Tk_var()
    top = Toplevel1 (w)
    bat_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("823x567+233+52")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("Bolt Analysis Tool - BAT")
        top.configure(cursor="arrow")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="File")
        self.sub_menu.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                command=bat_gui_support.open_inp_menu,
                font="TkMenuFont",
                foreground="#000000",
                label="Open *.inp File")
        self.sub_menu.add_separator(
                background="#d9d9d9")
        self.sub_menu.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                command=bat_gui_support.quit_menu,
                font="TkMenuFont",
                foreground="#000000",
                label="Exit")
        self.sub_menu1 = tk.Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="Help")
        self.sub_menu1.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                command=bat_gui_support.info_menu,
                font="TkMenuFont",
                foreground="#000000",
                label="Info")

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook = ttk.Notebook(top)
        self.TNotebook.place(relx=0.024, rely=0.035, relheight=0.929
                , relwidth=0.949)
        self.TNotebook.configure(takefocus="")
        self.TNotebook.configure(cursor="fleur")
        self.TNotebook_Joint_Input = tk.Frame(self.TNotebook)
        self.TNotebook.add(self.TNotebook_Joint_Input, padding=3)
        self.TNotebook.tab(0, text="Bolt",compound="left",underline="-1",)
        self.TNotebook_t1 = tk.Frame(self.TNotebook)
        self.TNotebook.add(self.TNotebook_t1, padding=3)
        self.TNotebook.tab(1, text="Clamped Parts", compound="none"
                ,underline="-1", )
        self.TNotebook_t2 = tk.Frame(self.TNotebook)
        self.TNotebook.add(self.TNotebook_t2, padding=3)
        self.TNotebook.tab(2, text="FOS",compound="none",underline="-1",)
        self.TNotebook_Loads = tk.Frame(self.TNotebook)
        self.TNotebook.add(self.TNotebook_Loads, padding=3)
        self.TNotebook.tab(3, text="Loads",compound="left",underline="-1",)
        self.TNotebook_Calculate = tk.Frame(self.TNotebook)
        self.TNotebook.add(self.TNotebook_Calculate, padding=3)
        self.TNotebook.tab(4, text="Calculate",compound="none",underline="-1",)

        self.Labelframe_Bolt_Def = tk.LabelFrame(self.TNotebook_Joint_Input)
        self.Labelframe_Bolt_Def.place(relx=0.024, rely=0.176, relheight=0.798
                , relwidth=0.955)
        self.Labelframe_Bolt_Def.configure(relief='groove')
        self.Labelframe_Bolt_Def.configure(text='''Bolt Definition''')

        self.TCombobox_Bolt = ttk.Combobox(self.Labelframe_Bolt_Def)
        self.TCombobox_Bolt.place(relx=0.288, rely=0.155, relheight=0.065
                , relwidth=0.284, bordermode='ignore')
        self.TCombobox_Bolt.configure(textvariable=bat_gui_support.combo_bolt)
        self.TCombobox_Bolt.configure(takefocus="")

        self.Label_Jt = tk.Label(self.Labelframe_Bolt_Def)
        self.Label_Jt.place(relx=0.03, rely=0.078, height=26, width=158
                , bordermode='ignore')
        self.Label_Jt.configure(activebackground="#f9f9f9")
        self.Label_Jt.configure(anchor='e')
        self.Label_Jt.configure(text='''Joint MOS Type:''')

        self.Radiobutton_Jt_min = tk.Radiobutton(self.Labelframe_Bolt_Def)
        self.Radiobutton_Jt_min.place(relx=0.273, rely=0.075, relheight=0.068
                , relwidth=0.153, bordermode='ignore')
        self.Radiobutton_Jt_min.configure(activebackground="#f9f9f9")
        self.Radiobutton_Jt_min.configure(justify='left')
        self.Radiobutton_Jt_min.configure(text='''MIN (STD)''')
        self.Radiobutton_Jt_min.configure(value="0")
        self.Radiobutton_Jt_min.configure(variable=bat_gui_support.joint_mos_type)

        self.Radiobutton_Jt_mean = tk.Radiobutton(self.Labelframe_Bolt_Def)
        self.Radiobutton_Jt_mean.place(relx=0.44, rely=0.078, relheight=0.065
                , relwidth=0.152, bordermode='ignore')
        self.Radiobutton_Jt_mean.configure(activebackground="#f9f9f9")
        self.Radiobutton_Jt_mean.configure(justify='left')
        self.Radiobutton_Jt_mean.configure(text='''MEAN''')
        self.Radiobutton_Jt_mean.configure(value="1")
        self.Radiobutton_Jt_mean.configure(variable=bat_gui_support.joint_mos_type)

        self.Label_Bolt = tk.Label(self.Labelframe_Bolt_Def)
        self.Label_Bolt.place(relx=0.03, rely=0.155, height=26, width=158
                , bordermode='ignore')
        self.Label_Bolt.configure(activebackground="#f9f9f9")
        self.Label_Bolt.configure(anchor='e')
        self.Label_Bolt.configure(text='''Bolt:''')

        self.Label_Bolt_Material = tk.Label(self.Labelframe_Bolt_Def)
        self.Label_Bolt_Material.place(relx=0.03, rely=0.235, height=26
                , width=158, bordermode='ignore')
        self.Label_Bolt_Material.configure(activebackground="#f9f9f9")
        self.Label_Bolt_Material.configure(anchor='e')
        self.Label_Bolt_Material.configure(text='''Bolt Material:''')

        self.TCombobox_Bolt_Material = ttk.Combobox(self.Labelframe_Bolt_Def)
        self.TCombobox_Bolt_Material.place(relx=0.288, rely=0.235
                , relheight=0.065, relwidth=0.284, bordermode='ignore')
        self.TCombobox_Bolt_Material.configure(textvariable=bat_gui_support.combo_bolt_mat)
        self.TCombobox_Bolt_Material.configure(takefocus="")
        self.TCombobox_Bolt_Material.configure(cursor="xterm")

        self.TLabel1 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel1.place(relx=0.027, rely=0.415, height=26, width=267
                , bordermode='ignore')
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(anchor='e')
        self.TLabel1.configure(justify='left')
        self.TLabel1.configure(text='''Coefficient of Friction - Bolt Head:''')

        self.TLabel2 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel2.place(relx=0.47, rely=0.338, height=26, width=56
                , bordermode='ignore')
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief="flat")
        self.TLabel2.configure(anchor='center')
        self.TLabel2.configure(justify='left')
        self.TLabel2.configure(text='''MIN''')

        self.TLabel2_1 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel2_1.place(relx=0.652, rely=0.338, height=26, width=57
                , bordermode='ignore')
        self.TLabel2_1.configure(background="#d9d9d9")
        self.TLabel2_1.configure(foreground="#000000")
        self.TLabel2_1.configure(font="TkDefaultFont")
        self.TLabel2_1.configure(relief="flat")
        self.TLabel2_1.configure(anchor='center')
        self.TLabel2_1.configure(justify='left')
        self.TLabel2_1.configure(text='''MAX''')

        self.Entry_Cof_Head_Min = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Cof_Head_Min.place(relx=0.44, rely=0.415, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Cof_Head_Min.configure(background="white")
        self.Entry_Cof_Head_Min.configure(font="TkFixedFont")
        self.Entry_Cof_Head_Min.configure(selectbackground="#c4c4c4")

        self.Entry_Cof_Head_Max = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Cof_Head_Max.place(relx=0.621, rely=0.415, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Cof_Head_Max.configure(background="white")
        self.Entry_Cof_Head_Max.configure(font="TkFixedFont")
        self.Entry_Cof_Head_Max.configure(selectbackground="#c4c4c4")

        self.TLabel1_8 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel1_8.place(relx=0.027, rely=0.488, height=26, width=267
                , bordermode='ignore')
        self.TLabel1_8.configure(background="#d9d9d9")
        self.TLabel1_8.configure(foreground="#000000")
        self.TLabel1_8.configure(font="TkDefaultFont")
        self.TLabel1_8.configure(relief="flat")
        self.TLabel1_8.configure(anchor='e')
        self.TLabel1_8.configure(justify='left')
        self.TLabel1_8.configure(text='''Coefficient of Friction - Thread:''')

        self.Entry_Cof_Thread_Min = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Cof_Thread_Min.place(relx=0.44, rely=0.495, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Cof_Thread_Min.configure(background="white")
        self.Entry_Cof_Thread_Min.configure(font="TkFixedFont")
        self.Entry_Cof_Thread_Min.configure(selectbackground="#c4c4c4")

        self.Entry_Cof_Thread_Max = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Cof_Thread_Max.place(relx=0.621, rely=0.495, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Cof_Thread_Max.configure(background="white")
        self.Entry_Cof_Thread_Max.configure(font="TkFixedFont")
        self.Entry_Cof_Thread_Max.configure(selectbackground="#c4c4c4")

        self.TLabel1_9 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel1_9.place(relx=0.212, rely=0.675, height=26, width=166
                , bordermode='ignore')
        self.TLabel1_9.configure(background="#d9d9d9")
        self.TLabel1_9.configure(foreground="#000000")
        self.TLabel1_9.configure(font="TkDefaultFont")
        self.TLabel1_9.configure(relief="flat")
        self.TLabel1_9.configure(anchor='e')
        self.TLabel1_9.configure(justify='left')
        self.TLabel1_9.configure(text='''Tightening Torque:''')

        self.TSeparator1 = ttk.Separator(self.Labelframe_Bolt_Def)
        self.TSeparator1.place(relx=0.042, rely=0.615, relwidth=0.921
                , bordermode='ignore')

        self.Entry_Tight_Torque = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Tight_Torque.place(relx=0.47, rely=0.675, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Tight_Torque.configure(background="white")
        self.Entry_Tight_Torque.configure(font="TkFixedFont")
        self.Entry_Tight_Torque.configure(selectbackground="#c4c4c4")

        self.TLabel2_11 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel2_11.place(relx=0.621, rely=0.675, height=26, width=57
                , bordermode='ignore')
        self.TLabel2_11.configure(background="#d9d9d9")
        self.TLabel2_11.configure(foreground="#000000")
        self.TLabel2_11.configure(font="TkDefaultFont")
        self.TLabel2_11.configure(relief="flat")
        self.TLabel2_11.configure(anchor='center')
        self.TLabel2_11.configure(justify='left')
        self.TLabel2_11.configure(text='''Nm''')

        self.TLabel1_10 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel1_10.place(relx=0.015, rely=0.753, height=26, width=313
                , bordermode='ignore')
        self.TLabel1_10.configure(background="#d9d9d9")
        self.TLabel1_10.configure(foreground="#000000")
        self.TLabel1_10.configure(font="TkDefaultFont")
        self.TLabel1_10.configure(relief="flat")
        self.TLabel1_10.configure(anchor='e')
        self.TLabel1_10.configure(justify='left')
        self.TLabel1_10.configure(text='''Torque Tolerance of Tightening Device:''')

        self.TLabel2_12 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel2_12.place(relx=0.621, rely=0.753, height=26, width=57
                , bordermode='ignore')
        self.TLabel2_12.configure(background="#d9d9d9")
        self.TLabel2_12.configure(foreground="#000000")
        self.TLabel2_12.configure(font="TkDefaultFont")
        self.TLabel2_12.configure(relief="flat")
        self.TLabel2_12.configure(anchor='center')
        self.TLabel2_12.configure(justify='left')
        self.TLabel2_12.configure(text='''Nm''')

        self.Entry_Torque_Tol = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Torque_Tol.place(relx=0.47, rely=0.753, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Torque_Tol.configure(background="white")
        self.Entry_Torque_Tol.configure(font="TkFixedFont")
        self.Entry_Torque_Tol.configure(selectbackground="#c4c4c4")

        self.TLabel1_11 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel1_11.place(relx=0.015, rely=0.83, height=26, width=313
                , bordermode='ignore')
        self.TLabel1_11.configure(background="#d9d9d9")
        self.TLabel1_11.configure(foreground="#000000")
        self.TLabel1_11.configure(font="TkDefaultFont")
        self.TLabel1_11.configure(relief="flat")
        self.TLabel1_11.configure(anchor='e')
        self.TLabel1_11.configure(justify='left')
        self.TLabel1_11.configure(text='''Locking Device Used:''')

        self.TLabel1_1 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel1_1.place(relx=0.015, rely=0.91, height=26, width=313
                , bordermode='ignore')
        self.TLabel1_1.configure(background="#d9d9d9")
        self.TLabel1_1.configure(foreground="#000000")
        self.TLabel1_1.configure(font="TkDefaultFont")
        self.TLabel1_1.configure(relief="flat")
        self.TLabel1_1.configure(anchor='e')
        self.TLabel1_1.configure(justify='left')
        self.TLabel1_1.configure(text='''Loading Plane Factor:''')

        self.Radiobutton_Lock_No = tk.Radiobutton(self.Labelframe_Bolt_Def)
        self.Radiobutton_Lock_No.place(relx=0.456, rely=0.835, relheight=0.058
                , relwidth=0.102, bordermode='ignore')
        self.Radiobutton_Lock_No.configure(activebackground="#f9f9f9")
        self.Radiobutton_Lock_No.configure(justify='left')
        self.Radiobutton_Lock_No.configure(text='''NO''')
        self.Radiobutton_Lock_No.configure(value="0")
        self.Radiobutton_Lock_No.configure(variable=bat_gui_support.locking_device)
        self.Radiobutton_Lock_No.bind('<Button-1>',lambda e:bat_gui_support.locking_device_no(e))

        self.Radiobutton_Lock_Yes = tk.Radiobutton(self.Labelframe_Bolt_Def)
        self.Radiobutton_Lock_Yes.place(relx=0.583, rely=0.835, relheight=0.058
                , relwidth=0.102, bordermode='ignore')
        self.Radiobutton_Lock_Yes.configure(activebackground="#f9f9f9")
        self.Radiobutton_Lock_Yes.configure(justify='left')
        self.Radiobutton_Lock_Yes.configure(text='''YES''')
        self.Radiobutton_Lock_Yes.configure(value="1")
        self.Radiobutton_Lock_Yes.configure(variable=bat_gui_support.locking_device)
        self.Radiobutton_Lock_Yes.bind('<Button-1>',lambda e:bat_gui_support.locking_device_yes(e))

        self.TLabel2_13 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel2_13.place(relx=0.894, rely=0.835, height=26, width=57
                , bordermode='ignore')
        self.TLabel2_13.configure(background="#d9d9d9")
        self.TLabel2_13.configure(foreground="#000000")
        self.TLabel2_13.configure(font="TkDefaultFont")
        self.TLabel2_13.configure(relief="flat")
        self.TLabel2_13.configure(anchor='center')
        self.TLabel2_13.configure(justify='left')
        self.TLabel2_13.configure(text='''Nm''')

        self.Entry_Prevailing_Torque = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Prevailing_Torque.place(relx=0.802, rely=0.835, height=25
                , relwidth=0.081, bordermode='ignore')
        self.Entry_Prevailing_Torque.configure(background="white")
        self.Entry_Prevailing_Torque.configure(font="TkFixedFont")
        self.Entry_Prevailing_Torque.configure(selectbackground="#c4c4c4")

        self.TLabel2_2 = ttk.Label(self.Labelframe_Bolt_Def)
        self.TLabel2_2.place(relx=0.727, rely=0.835, height=26, width=56
                , bordermode='ignore')
        self.TLabel2_2.configure(background="#d9d9d9")
        self.TLabel2_2.configure(foreground="#000000")
        self.TLabel2_2.configure(font="TkDefaultFont")
        self.TLabel2_2.configure(relief="flat")
        self.TLabel2_2.configure(anchor='center')
        self.TLabel2_2.configure(justify='left')
        self.TLabel2_2.configure(text='''Tp:''')

        self.Entry_Loading_Plane_Factor = tk.Entry(self.Labelframe_Bolt_Def)
        self.Entry_Loading_Plane_Factor.place(relx=0.47, rely=0.91, height=25
                , relwidth=0.134, bordermode='ignore')
        self.Entry_Loading_Plane_Factor.configure(background="white")
        self.Entry_Loading_Plane_Factor.configure(font="TkFixedFont")
        self.Entry_Loading_Plane_Factor.configure(selectbackground="#c4c4c4")

        self.Label_Method = tk.Label(self.TNotebook_Joint_Input)
        self.Label_Method.place(relx=0.027, rely=0.04, height=26, width=111)
        self.Label_Method.configure(activebackground="#f9f9f9")
        self.Label_Method.configure(anchor='e')
        self.Label_Method.configure(text='''Method:''')

        self.Radiobutton_Esapss = tk.Radiobutton(self.TNotebook_Joint_Input)
        self.Radiobutton_Esapss.place(relx=0.171, rely=0.04, relheight=0.052
                , relwidth=0.184)
        self.Radiobutton_Esapss.configure(activebackground="#f9f9f9")
        self.Radiobutton_Esapss.configure(justify='left')
        self.Radiobutton_Esapss.configure(text='''ESA PSS-03''')
        self.Radiobutton_Esapss.configure(value="0")
        self.Radiobutton_Esapss.configure(variable=bat_gui_support.method_sel)
        self.Radiobutton_Esapss.bind('<Button-1>',lambda e:bat_gui_support.radio_esapss(e))

        self.Radiobutton_VDI2230 = tk.Radiobutton(self.TNotebook_Joint_Input)
        self.Radiobutton_VDI2230.place(relx=0.643, rely=0.04, relheight=0.05
                , relwidth=0.2)
        self.Radiobutton_VDI2230.configure(activebackground="#f9f9f9")
        self.Radiobutton_VDI2230.configure(justify='left')
        self.Radiobutton_VDI2230.configure(text='''VDI 2230''')
        self.Radiobutton_VDI2230.configure(value="2")
        self.Radiobutton_VDI2230.configure(variable=bat_gui_support.method_sel)
        self.Radiobutton_VDI2230.bind('<Button-1>',lambda e:bat_gui_support.radio_vdi2230(e))

        self.Radiobutton_ECSS = tk.Radiobutton(self.TNotebook_Joint_Input)
        self.Radiobutton_ECSS.place(relx=0.401, rely=0.04, relheight=0.052
                , relwidth=0.199)
        self.Radiobutton_ECSS.configure(activebackground="#f9f9f9")
        self.Radiobutton_ECSS.configure(justify='left')
        self.Radiobutton_ECSS.configure(text='''ECSS bla''')
        self.Radiobutton_ECSS.configure(value="1")
        self.Radiobutton_ECSS.configure(variable=bat_gui_support.method_sel)
        self.Radiobutton_ECSS.bind('<Button-1>',lambda e:bat_gui_support.radio_ecss(e))

        self.Label1 = tk.Label(self.TNotebook_Joint_Input)
        self.Label1.place(relx=0.03, rely=0.102, height=25, width=111)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='e')
        self.Label1.configure(text='''Project Title:''')

        self.Entry1 = tk.Entry(self.TNotebook_Joint_Input)
        self.Entry1.place(relx=0.2, rely=0.102,height=25, relwidth=0.778)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")

        self.Labelframe2 = tk.LabelFrame(self.TNotebook_t1)
        self.Labelframe2.place(relx=0.026, rely=0.04, relheight=0.924
                , relwidth=0.941)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(text='''Clamped Parts Definition''')

        self.Label3 = tk.Label(self.Labelframe2)
        self.Label3.place(relx=0.014, rely=0.084, height=24, width=317
                , bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(anchor='e')
        self.Label3.configure(text='''Minimum CoF between Clamped Parts:''')

        self.Label3_7 = tk.Label(self.Labelframe2)
        self.Label3_7.place(relx=0.014, rely=0.212, height=24, width=318
                , bordermode='ignore')
        self.Label3_7.configure(activebackground="#f9f9f9")
        self.Label3_7.configure(anchor='e')
        self.Label3_7.configure(text='''Through Hole Diameter:''')

        self.Label3_8 = tk.Label(self.Labelframe2)
        self.Label3_8.place(relx=0.014, rely=0.147, height=25, width=318
                , bordermode='ignore')
        self.Label3_8.configure(activebackground="#f9f9f9")
        self.Label3_8.configure(anchor='e')
        self.Label3_8.configure(text='''Number of Shear Planes:''')

        self.Entry_cof_clamp = tk.Entry(self.Labelframe2)
        self.Entry_cof_clamp.place(relx=0.473, rely=0.084, height=25
                , relwidth=0.172, bordermode='ignore')
        self.Entry_cof_clamp.configure(background="white")
        self.Entry_cof_clamp.configure(font="TkFixedFont")
        self.Entry_cof_clamp.configure(selectbackground="#c4c4c4")

        self.Spinbox_nmbr_shear_planes = tk.Spinbox(self.Labelframe2, from_=1.0, to=100.0)
        self.Spinbox_nmbr_shear_planes.place(relx=0.473, rely=0.147
                , relheight=0.054, relwidth=0.173, bordermode='ignore')
        self.Spinbox_nmbr_shear_planes.configure(activebackground="#f9f9f9")
        self.Spinbox_nmbr_shear_planes.configure(background="white")
        self.Spinbox_nmbr_shear_planes.configure(font="TkDefaultFont")
        self.Spinbox_nmbr_shear_planes.configure(highlightbackground="black")
        self.Spinbox_nmbr_shear_planes.configure(selectbackground="#c4c4c4")
        self.Spinbox_nmbr_shear_planes.configure(textvariable=bat_gui_support.spinbox_nmbr_shear_planes)

        self.Entry_throughhole_diameter = tk.Entry(self.Labelframe2)
        self.Entry_throughhole_diameter.place(relx=0.473, rely=0.212, height=25
                , relwidth=0.172, bordermode='ignore')
        self.Entry_throughhole_diameter.configure(background="white")
        self.Entry_throughhole_diameter.configure(font="TkFixedFont")
        self.Entry_throughhole_diameter.configure(selectbackground="#c4c4c4")

        self.Label4 = tk.Label(self.Labelframe2)
        self.Label4.place(relx=0.655, rely=0.216, height=25, width=59
                , bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''mm''')

        self.Label3_1 = tk.Label(self.Labelframe2)
        self.Label3_1.place(relx=0.014, rely=0.274, height=24, width=318
                , bordermode='ignore')
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(anchor='e')
        self.Label3_1.configure(text='''Substitutional Diameter - DA:''')

        self.Entry_subst_da = tk.Entry(self.Labelframe2)
        self.Entry_subst_da.place(relx=0.473, rely=0.274, height=25
                , relwidth=0.172, bordermode='ignore')
        self.Entry_subst_da.configure(background="white")
        self.Entry_subst_da.configure(font="TkFixedFont")
        self.Entry_subst_da.configure(selectbackground="#c4c4c4")

        self.Label4_10 = tk.Label(self.Labelframe2)
        self.Label4_10.place(relx=0.655, rely=0.281, height=25, width=59
                , bordermode='ignore')
        self.Label4_10.configure(activebackground="#f9f9f9")
        self.Label4_10.configure(text='''mm''')

        self.Label3_9 = tk.Label(self.Labelframe2)
        self.Label3_9.place(relx=0.014, rely=0.337, height=25, width=318
                , bordermode='ignore')
        self.Label3_9.configure(activebackground="#f9f9f9")
        self.Label3_9.configure(anchor='e')
        self.Label3_9.configure(text='''Use Shim:''')

        self.Radiobutton_shim_yes = tk.Radiobutton(self.Labelframe2)
        self.Radiobutton_shim_yes.place(relx=0.473, rely=0.337, relheight=0.054
                , relwidth=0.075, bordermode='ignore')
        self.Radiobutton_shim_yes.configure(activebackground="#f9f9f9")
        self.Radiobutton_shim_yes.configure(justify='left')
        self.Radiobutton_shim_yes.configure(text='''YES''')
        self.Radiobutton_shim_yes.configure(value="0")
        self.Radiobutton_shim_yes.configure(variable=bat_gui_support.use_shim)

        self.Radiobutton_shim_no = tk.Radiobutton(self.Labelframe2)
        self.Radiobutton_shim_no.place(relx=0.568, rely=0.337, relheight=0.054
                , relwidth=0.075, bordermode='ignore')
        self.Radiobutton_shim_no.configure(activebackground="#f9f9f9")
        self.Radiobutton_shim_no.configure(justify='left')
        self.Radiobutton_shim_no.configure(text='''NO''')
        self.Radiobutton_shim_no.configure(value="1")
        self.Radiobutton_shim_no.configure(variable=bat_gui_support.use_shim)

        self.Button_del_cp = tk.Button(self.Labelframe2)
        self.Button_del_cp.place(relx=0.805, rely=0.562, height=31, width=101
                , bordermode='ignore')
        self.Button_del_cp.configure(activebackground="#f9f9f9")
        self.Button_del_cp.configure(text='''DELETE''')

        self.Labelframe3 = tk.LabelFrame(self.Labelframe2)
        self.Labelframe3.place(relx=0.055, rely=0.41, relheight=0.207
                , relwidth=0.708, bordermode='ignore')
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(text='''Define Clamp Part (i)''')

        self.TCombobox_cp_mat = ttk.Combobox(self.Labelframe3)
        self.TCombobox_cp_mat.place(relx=0.044, rely=0.521, relheight=0.271
                , relwidth=0.322, bordermode='ignore')
        self.TCombobox_cp_mat.configure(textvariable=bat_gui_support.combobox)
        self.TCombobox_cp_mat.configure(takefocus="")

        self.Label5 = tk.Label(self.Labelframe3)
        self.Label5.place(relx=0.044, rely=0.208, height=26, width=162
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Material:''')

        self.Label5_11 = tk.Label(self.Labelframe3)
        self.Label5_11.place(relx=0.43, rely=0.208, height=26, width=129
                , bordermode='ignore')
        self.Label5_11.configure(activebackground="#f9f9f9")
        self.Label5_11.configure(text='''Thickness:''')

        self.Entry_cp_thk = tk.Entry(self.Labelframe3)
        self.Entry_cp_thk.place(relx=0.43, rely=0.521, height=25, relwidth=0.243
                , bordermode='ignore')
        self.Entry_cp_thk.configure(background="white")
        self.Entry_cp_thk.configure(font="TkFixedFont")
        self.Entry_cp_thk.configure(selectbackground="#c4c4c4")

        self.Button_add_cp = tk.Button(self.Labelframe3)
        self.Button_add_cp.place(relx=0.829, rely=0.313, height=41, width=71
                , bordermode='ignore')
        self.Button_add_cp.configure(activebackground="#f9f9f9")
        self.Button_add_cp.configure(text='''ADD''')

        self.Label4_2 = tk.Label(self.Labelframe3)
        self.Label4_2.place(relx=0.674, rely=0.521, height=25, width=59
                , bordermode='ignore')
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(text='''mm''')

        self.Button_cp_down = tk.Button(self.Labelframe2)
        self.Button_cp_down.place(relx=0.805, rely=0.475, height=31, width=101
                , bordermode='ignore')
        self.Button_cp_down.configure(activebackground="#f9f9f9")
        self.Button_cp_down.configure(text='''DOWN''')

        self.Button_cp_up = tk.Button(self.Labelframe2)
        self.Button_cp_up.place(relx=0.805, rely=0.389, height=31, width=101
                , bordermode='ignore')
        self.Button_cp_up.configure(activebackground="#f9f9f9")
        self.Button_cp_up.configure(text='''UP''')

        self.Listbox_clamped_parts = tk.Listbox(self.Labelframe2)
        self.Listbox_clamped_parts.place(relx=0.055, rely=0.648, relheight=0.315
                , relwidth=0.895, bordermode='ignore')
        self.Listbox_clamped_parts.configure(background="white")
        self.Listbox_clamped_parts.configure(font="TkFixedFont")
        self.Listbox_clamped_parts.configure(selectbackground="#c4c4c4")

        self.Labelframe1 = tk.LabelFrame(self.TNotebook_t2)
        self.Labelframe1.place(relx=0.0, rely=0.0, relheight=0.002
                , relwidth=0.001)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(text='''Factors of Safety - FOS''')

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.0, rely=0.0, height=1, width=1
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='e')
        self.Label2.configure(text='''Factor of Safety Yield - FOS_y:''')

        self.Label2_1 = tk.Label(self.Labelframe1)
        self.Label2_1.place(relx=0.0, rely=0.0, height=1, width=1
                , bordermode='ignore')
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(anchor='e')
        self.Label2_1.configure(text='''Factor of Safety Ultimate - FOS_u:''')

        self.Label2_2 = tk.Label(self.Labelframe1)
        self.Label2_2.place(relx=0.0, rely=0.0, height=1, width=1
                , bordermode='ignore')
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(anchor='e')
        self.Label2_2.configure(text='''Factor of Safety Gapping - FOS_gap:''')

        self.Label2_3 = tk.Label(self.Labelframe1)
        self.Label2_3.place(relx=0.0, rely=0.0, height=1, width=1
                , bordermode='ignore')
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(anchor='e')
        self.Label2_3.configure(text='''Factor of Safety Slippage - FOS_slip:''')

        self.Entry_fos_y = tk.Entry(self.Labelframe1)
        self.Entry_fos_y.place(relx=0.0, rely=0.0, height=25, relwidth=116.0
                , bordermode='ignore')
        self.Entry_fos_y.configure(background="white")
        self.Entry_fos_y.configure(font="TkFixedFont")
        self.Entry_fos_y.configure(selectbackground="#c4c4c4")

        self.Entry_fos_u = tk.Entry(self.Labelframe1)
        self.Entry_fos_u.place(relx=0.0, rely=0.0, height=25, relwidth=116.0
                , bordermode='ignore')
        self.Entry_fos_u.configure(background="white")
        self.Entry_fos_u.configure(font="TkFixedFont")
        self.Entry_fos_u.configure(selectbackground="#c4c4c4")

        self.Entry_fos_slip = tk.Entry(self.Labelframe1)
        self.Entry_fos_slip.place(relx=0.0, rely=0.0, height=25, relwidth=116.0
                , bordermode='ignore')
        self.Entry_fos_slip.configure(background="white")
        self.Entry_fos_slip.configure(font="TkFixedFont")
        self.Entry_fos_slip.configure(selectbackground="#c4c4c4")

        self.Entry_fos_gap = tk.Entry(self.Labelframe1)
        self.Entry_fos_gap.place(relx=0.0, rely=0.0, height=25, relwidth=116.0
                , bordermode='ignore')
        self.Entry_fos_gap.configure(background="white")
        self.Entry_fos_gap.configure(font="TkFixedFont")
        self.Entry_fos_gap.configure(selectbackground="#c4c4c4")
